# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'

# Uncomment this line if you're using Swift
use_frameworks!

target 'Stopwatch' do

  pod 'googleapis', :path => '.'
  pod 'CryptoSwift', '~> 0.7.1'
  pod 'BigInt', '~> 3.0.1'
  pod 'SwiftyBase64', '~> 1.1.1'

end


