#!/bin/sh

echo "Install Cocoapod dependencies"
pod install

echo "Open the project workspace in Xcode"
open stickynotes.xcworkspace

echo "Now press the run button!"
echo "Be sure that your server is running."


